config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  resources :posts
  resources :tags, only: [:show]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
mount_uploader :image, ImageUploader

has_many :taggings
has_many :tags, through: :taggings

validates :title, :summary, :body, presence: true
def all_tags
self.tags.map(&:name).join(', ')
end

def all_tags=(names)
self.tags = names.split(',').map do |name|
Tag.where(name: name.strip).first_or_create
end
end
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :taggings
    has_many :posts, through: :taggings

    def self.counts
        self.select("name, count(taggings.tag_id) as count").joins(:taggings).group("taggings.tag_id")
    end   
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
add_flash_types :success, :danger, :info, :warning
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

before_action :set_post, only: [ :show, :edit, :update, :destroy]
    def index
@posts = Post.all
end

def show
end
def new
@post = Post.new
end

def create
@post = Post.new(post_params)
if @post.save
    redirect_to @post, success: "Articles successfully created"
else
    render :new, danger: "Articles not created"
end
end

def edit
end

def update 
if @post.update(post_params)
    redirect_to @post, success: 'Articles update successfully'
else
    render :edit, danger: "Error, Article not updated"
end
end
def destroy
@post.destroy
redirect_to posts_path, success: 'Articles deleted successfully'
end
private 
def set_post 
@post = Post.find(params[:id])
end
def post_params
params.require(:post).permit(:title,:summary,:body, :image, :all_tags)
end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
def show
    @tag = Tag.find_by(name: params[:id])
    @posts = @tag.posts
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
    def tag_cloud(tags, classes)
        max = tags.sort_by(&:count).last
        tags.each do |tag|
        index = tag.count.to_f / max.count * (classes.size - 1)
        yield(tag, classes[index.round])
        end
    end     
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BLOG</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
<nav class="navbar navbar-light bg-warning">
    <ul class="nav navbar-nav ">
      <li class="nav-item stats">
        <a class="nav-link col-md-12 btn btn-secondary text-light" href="<%= posts_path %>">Статті</a>
      </li>
       <li class="nav-item">
        <%= link_to 'Нова стаття', new_post_path, class: 'btn btn-secondary'%>
</li>
      
    </ul>
</nav>
</div>

<div class = 'container main'>
<div class = 'row'>
<div class = 'col-md-12'>
<%flash.each do|name, message|%>
<div class = 'alert alert-<%= name%>'>
<%= message %>
</div>
<%end%>
</div>
</div>

<div class="row">
<div class="col-md-8">
    <%= yield %>
</div>


</div>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<% if @post.errors.any? %>
<div class='alert alert-danger'>
<h5><%= t('common.errors')%></h5>
<ul>
<% @post.errors.full_messages.each do |message|%>
<li><%= message %></li>
<% end %>
</ul>
</div>
<% end%>
<%= form_for @post, html: {multipart: true } do|f| %>
<div class="form-group">
<%= f.label :title %>
<%= f.text_field :title, class: 'form-control' %>
</div>

<div class="form-group">
<%= f.label :summary %>
<%= f.text_area :summary, class: 'form-control' %>
</div>

<div class="form-group">
<%= f.label :body %>
<%= f.text_area :body, class: 'form-control' %>
</div>

<div class="form-group mt-4">
<%= f.label :body %>
<%= f.file_field  :image %>
</div>

<div class="form-group">
<%= f.submit t(".submit", action: @post.new_record? ? "Створити" : "Змінити") , class: 'btn btn-warning'%>
<%= link_to t('common.back'), :back, class: 'btn btn-secondary'%>
</div>
<%end%>

app/views/posts/_post.html.erb
<article class="post">  
<section class="post-head"> 
<h2 class = "text-decoration-none bg-light"><%= link_to post.title, post_path(post) %></h2>
<small>
<time><%= post.created_at.to_date.strftime("%d %B, %Y")%></time>
<%= link_to t('common.change'), edit_post_path(post)%>


</small>
</section> 
<section class="post-summary clearfix"> 
<%= image_tag post.image.url(:thumb), class: 'img-thumbnail thumb' if post.image?%>
<%= post.summary%>
</section> 
<p>By Antonovych Vadym</p>



</article>

app/views/posts/edit.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form'%>

app/views/posts/index.html.erb
<h1><%= t('.title')%></h1>

<%= render @posts%>

app/views/posts/new.html.erb
<h1><%= t('.title')%></h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<article class="post">  
<section class="post-head"> 
<h1><%=  @post.title%></h1>
<small>
<time><%= @post.created_at.to_date.strftime("%d %B, %Y")%></time>
<%= link_to t('common.change'), edit_post_path(@post)%>


</small>
</section> 
<section class="post-body"> 
<%= image_tag @post.image.url(:large), class: "img-show" if @post.image? %>
<%= @post.body%>
</section> 
</article>